# Generated by Django 6.0.2 on 2026-02-17 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ejercicios", "0003_curso_ejercicio_curso"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ejercicio",
            name="curso",
        ),
        migrations.AddField(
            model_name="curso",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("A1", "Acceso (A1)"),
                    ("A2", "Plataforma (A2)"),
                    ("B1", "Umbral (B1)"),
                    ("B2", "Avanzado (B2)"),
                    ("C1", "Dominio Eficaz (C1)"),
                    ("C2", "Maestría (C2)"),
                ],
                default="A1",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="ejercicio",
            name="tipo",
            field=models.CharField(
                choices=[("P", "Práctica"), ("E", "Evaluación")],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="descripcion",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="curso",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ejercicio",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ejercicio",
            name="frase",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="ejercicio",
            name="nivel",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="ejercicio",
            name="palabra_correcta",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="Leccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("contenido_teorico", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=1)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecciones",
                        to="ejercicios.curso",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Lecciones",
                "ordering": ["orden"],
            },
        ),
        migrations.AddField(
            model_name="ejercicio",
            name="leccion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ejercicios",
                to="ejercicios.leccion",
            ),
        ),
        migrations.CreateModel(
            name="PerfilEstudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntos", models.IntegerField(default=0)),
                ("ejercicios_completados", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
