# Generated by Django 4.2.7 on 2026-02-18 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "ejercicios",
            "0004_remove_ejercicio_curso_curso_nivel_ejercicio_tipo_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leccion",
            options={},
        ),
        migrations.RemoveField(
            model_name="curso",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="curso",
            name="estudiantes",
        ),
        migrations.RemoveField(
            model_name="curso",
            name="nivel",
        ),
        migrations.RemoveField(
            model_name="ejercicio",
            name="activo",
        ),
        migrations.RemoveField(
            model_name="ejercicio",
            name="creado_por",
        ),
        migrations.RemoveField(
            model_name="ejercicio",
            name="frase",
        ),
        migrations.RemoveField(
            model_name="ejercicio",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="leccion",
            name="contenido_teorico",
        ),
        migrations.RemoveField(
            model_name="leccion",
            name="orden",
        ),
        migrations.RemoveField(
            model_name="perfilestudiante",
            name="ejercicios_completados",
        ),
        migrations.RemoveField(
            model_name="perfilestudiante",
            name="puntos",
        ),
        migrations.AddField(
            model_name="perfilestudiante",
            name="nivel",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="curso",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="curso",
            name="profesor",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="ejercicio",
            name="leccion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ejercicios",
                to="ejercicios.leccion",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ejercicio",
            name="palabra_correcta",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="perfilestudiante",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil_ejercicios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
